#!/bin/sh

PATH=/app/bin:$PATH

set -e

cmd="$1"
shift

envsubst < /app/config.js.in > /app/build/config.js

case "$cmd" in
    start)
        exec serve -l 3000 -s build
        ;;

    wait)
        sleep infinity
        ;;

    help)
        echo Available commands:
        echo
        echo    start   - start API server
        echo    help    - show this message
        ;;

    *)
        echo Unknown command >&2
        "$0" help >&2
        exit 1
        ;;
esac
