#!/bin/sh

PATH=/app/bin:$PATH

set -e

cmd="$1"
shift

alembic upgrade head &&

case "$cmd" in
    start)
        exec uvicorn backend.main:app --host 0.0.0.0 --port 8000
        ;;

    wait)
        sleep infinity
        ;;

    help)
        echo Available commands:
        echo
        echo    start   - start API server
        echo    help    - show this message
        ;;

    *)
        echo Unknown command >&2
        "$0" help >&2
        exit 1
        ;;
esac
