#!/usr/bin/python


import base64
import os


def generate_password():
    tok = os.urandom(16)
    return base64.urlsafe_b64encode(tok).rstrip(b"=").decode("ascii")


def main():
    print("SQL_POSTGRES_USER=postgres")
    print("SQL_POSTGRES_PASSWORD=%s" % generate_password())
    print("SQL_BACKEND_USER=backend")
    print("SQL_BACKEND_PASSWORD=%s" % generate_password())
    print("")
    print("BACKEND_AUTH_SECRET=%s" % generate_password())


if __name__ == "__main__":
    main()
